"""Public model API."""

from .baseline import CenterNetBaseline, SharedCenterNetBaseline, SharedPathwayCenterNet
from .conditioning import (
    ByteTextConditioner,
    ClassEmbeddingConditioner,
    ConditioningOutput,
    HFPretrainedConditioner,
    LazyHFTextConditioner,
    LightweightTextConditioner,
    NoConditioner,
    build_conditioner,
    masked_mean,
    materialize_conditioners_for_state_dict,
    materialize_pretrained_conditioners,
)
from .config import (
    MODEL_PRESETS,
    PRESET_REGISTRY,
    ConditionerConfig,
    ImageEncoderConfig,
    ModelConfig,
    TextEncoderConfig,
    VAEConfig,
    get_model_preset,
    get_preset,
    list_model_presets,
    register_model_preset,
    register_preset,
)
from .detector import (
    CLASS_TEXTS,
    ConvImageEncoder,
    EarlyFusion,
    FloorPlanDetector,
    HeatmapHead,
    TextEncoderStub,
    VAEEncoderStub,
)
from .factory import build_model, create_model
from .presets import resolve_model_config

__all__ = [
    "ByteTextConditioner",
    "CenterNetBaseline",
    "CLASS_TEXTS",
    "ClassEmbeddingConditioner",
    "ConditionerConfig",
    "ConditioningOutput",
    "ConvImageEncoder",
    "EarlyFusion",
    "FloorPlanDetector",
    "HFPretrainedConditioner",
    "HeatmapHead",
    "ImageEncoderConfig",
    "LazyHFTextConditioner",
    "LightweightTextConditioner",
    "MODEL_PRESETS",
    "PRESET_REGISTRY",
    "ModelConfig",
    "NoConditioner",
    "SharedCenterNetBaseline",
    "SharedPathwayCenterNet",
    "TextEncoderConfig",
    "TextEncoderStub",
    "VAEConfig",
    "VAEEncoderStub",
    "build_conditioner",
    "build_model",
    "create_model",
    "get_model_preset",
    "get_preset",
    "list_model_presets",
    "masked_mean",
    "materialize_conditioners_for_state_dict",
    "materialize_pretrained_conditioners",
    "register_model_preset",
    "register_preset",
    "resolve_model_config",
]
